"""add_smth

Revision ID: 58cdf163b786
Revises: 68f83893d090
Create Date: 2024-11-24 11:18:11.564725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cdf163b786'
down_revision = '68f83893d090'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
