"""add_smth

Revision ID: 68f83893d090
Revises: 91068adb1ed5
Create Date: 2024-11-24 11:04:12.912379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f83893d090'
down_revision = '91068adb1ed5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tag', sa.Text(), nullable=False))
    op.drop_column('user_detailed_info', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_detailed_info', sa.Column('tag', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('user', 'tag')
    # ### end Alembic commands ###
