"""add_smth

Revision ID: 91068adb1ed5
Revises: 2aa7b70f8f24
Create Date: 2024-11-24 10:36:11.050566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91068adb1ed5'
down_revision = '2aa7b70f8f24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
