"""add_smth

Revision ID: edb1b3114d87
Revises: 36c20564359d
Create Date: 2024-12-08 11:06:20.313643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb1b3114d87'
down_revision = '36c20564359d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_detailed_info', sa.Column('updated_ts', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_detailed_info', 'updated_ts')
    # ### end Alembic commands ###
